# Site settings
permalink: /blog/:year/:month/:day/:title/
title: Redex
tagline: An Android Bytecode Optimizer
fbappid: ""
gacode: "UA-44373548-2"
description: >
  ReDex is an Android bytecode (dex) optimizer originally developed at Facebook. It provides a framework for reading, writing, and analyzing .dex files, and a set of optimization passes that use this framework to improve the bytecode. An APK optimized by ReDex should be smaller and faster than its source.
baseurl: "" # the subpath of your site, e.g. /nuclide/
url: "http://fbredex.com" # the base hostname & protocol for your site
ghrepo: "facebook/redex"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'rougeHighlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: :compressed

color:
  # Provides colour for background of top header of homepage
  primary: "#75c7a4"
  # Provides colour for background of elsewhere on site
  secondary: "#f9f9f9"
  # A color that will work for buttons laid on top of primary colour
  light: "#bef5de"
  # Color that will work for text on top of light color
  lighttext: "#fff"
  # Color of text in the top header of homepage, must be legible on top of primary color
  headertext: "#fff"
  # Color of text on top of the secondary color background
  bodytext: "#151515"
  # Background of fixed nav header - headertext color is used for mini logo text
  nav: "#fff"
  # Text of links in the nav
  navtext: "#fff"
  # Color of link underlines in the main body, and hover background color for links
  link: "#26d087"
